# NeON Build File (http://github.com/c4s4/neon)

extends: chandago/neon/golang.yml
default: [fmt, lint, test]
expose:  [fmt, lint, test, release]
# configuration: '~/.neon/github.yml'
# GITHUB_TOKEN: 'abcdefghijklmnopqrstuvwxyz0123456789'
