# NeON build file (http://github.com/c4s4/neon)

extends: chandago/neon/slides.yml
expose:  [clean, slides, publish, release, TITLE, OPTIONS]
configuration: '~/.neon/github.yml'
# GITHUB_TOKEN: 'abcdefghijklmnopqrstuvwxyz0123456789'

properties:
  TITLE:      "Slides Title"
  # OPTIONS:    '{ratio: "4:3"}'
  OPTIONS:    '{ratio: "16:9"}'
  BG_IMAGE:   'img/logo-sfbx.png'
  BG_ALPHA:   100
  BG_WIDTH:   20
  BG_IMAGE_X: 85
  BG_IMAGE_Y: 85
  BG_COLOR:   '#FFFFFF'
  TEXT_COLOR: '#000000'
  LINK_COLOR: '#0000AA'
