# NeON build file (http://github.com/c4s4/neon)

extends: chandago/neon/slides.yml
expose:  [clean, slides, TITLE, OPTIONS]

properties:
  TITLE:   'Slides Title'
  #OPTIONS: '{ratio: "4:3"}'
  OPTIONS: "{ratio: '16:9'}"
